on: push

jobs:
  build:
    runs-on: windows-2025-VS2026
    steps:
      - uses: actions/checkout@v6
      - run: New-Item -ItemType Junction -Path C:\r -Target "${{ github.workspace }}"
      - shell: pwsh
        working-directory: C:\r
        run: ./build.ps1
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: C:/r/out/release/DirectoryOpus-CSV-viewer-plugin.zip
      - uses: actions/upload-artifact@v4
        with:
          name: Build artifacts
          path: C:/r/out/release/DirectoryOpus-CSV-viewer-plugin.zip
